version: "3.1"

services:
  parrots_dont_tweet_api:
    image: parrots_dont_tweet:0.0.1
#    networks:
#      - parrot-network
#    depends_on:
#      - parrots_dont_tweet_db
    ports:
      - "3000:3000"
    environment:
      - DB_PORT=9200
      - API_PORT=3000

  #  parrots_dont_tweet_db:
  #    image: parrots_dont_tweet_db
  #    volumes:
  #      - elasticsearch-data:/var/lib/docker/volumes/docker_farm-data
  #    networks:
  #      - parrot-network

#networks:
#  parrot-network:
#
#volumes:
# elasticsearch-data:
#
#secrets:
# Use these instead?
