apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-dont-tweet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot-dont-tweet
  template:
    metadata:
      labels:
        app: parrot-dont-tweet
    spec:
      containers:
      - name: parrot-dont-tweet
        image: nkernis/parrots_dont_tweet:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: DB_PORT
            value: 9200
          - name: DB_HOST
            value: "elasticsearch_parrot"
          - name: DB_INDEX
            value: "trump-tweets"
          - name: API_PORT
            value: 3000
          - name: TWITTER_USER_ID
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: twitter.user.id
          - name: TWIT_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: twitter.consumer.key
          - name: TWIT_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: twitter.consumer.secret
          - name: TWIT_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: twitter.access.token
          - name: TWIT_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: twitter.access.token.secret
