apiVersion: v1
kind: Service
metadata:
  name: parrot-dont-tweet
  labels:
    app: parrot-dont-tweet
spec:
  type: NodePort
  selector:
    app: parrot-dont-tweet
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31118

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-dont-tweet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot-dont-tweet
  template:
    metadata:
      labels:
        app: parrot-dont-tweet
    spec:
      containers:
      - name: parrot-dont-tweet
        image: nginx
        # image: nkernis/parrots_dont_tweet:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
